
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 8
#define YY_END_OF_BUFFER 9
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[237] =
    {   0,
        0,    0,    9,    6,    6,    7,    6,    6,    6,    6,
        6,    6,    0,    0,    0,    1,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    4,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    5,
        5,    0,    0,    0,    0,    1,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    4,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    3,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,    3,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    3,    0,    3,    0,    0,
        3,    3,    0,    3,    3,    0,    0,    0,    0,    2,
        0,    0,    0,    2,    2,    2,    0,    0,    0,    0,

        0,    0,    0,    0,    3,    0,    0,    0,    3,    3,
        0,    0,    0,    0,    3,    0,    0,    3,    0,    0,
        3,    0,    3,    3,    0,    0,    0,    0,    2,    2,
        2,    0,    0,    2,    2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    1,    1,    6,
        7,    8,    1,    9,    1,    1,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       17,    1,   18,    1,   16,    1,   19,   20,   21,   22,

       23,   16,   16,   16,   24,   16,   16,   25,   26,   27,
       28,   29,   16,   30,   31,   32,   33,   34,   16,   35,
       16,   16,   36,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[37] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    7,    1,
        8,    9,   10,   11,    1,    4,   12,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,   13
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,    0,  689, 1148,   35,   37,  683,   39,   36,   55,
       18,   22,   57,   60,  669,  667,   72,   84,  653,  633,
      635,  629,   61,    0,  100,   60,   62,  612,  102,  118,
      123,  135,  148,  610, 1148,  594,  139,   89,  596,  162,
      197,   62,  115,  145,    0,   36,   88,   57,   91,  114,
      199,  213,    0,  209,  226,  217,  229,  585, 1148,  204,
     1148,    0,  239,  252,  587,  205,  217,  576,   30,  220,
      270,  293,  568,   97,  309,    0,  566, 1148,  288,  120,
      124,  228,  278,  311,  327,  156,  343,  558,  248,  314,
      359,  105,  185,  290,  303,  552,  323,  372,    0,  550,

      339,  346,  375,  388,  214,  423,  355,  385,  546,  396,
      353,  393,  542,  404,  453,  488, 1148,  279,  523,  536,
      283,  526,  412,  431,  560,  531,  364,  501,  508,  576,
      505,  308,  318,  508,    0,  414,  589,  605,  505,  383,
      425,  488,  487,  322,  376,  483,  494,  443,  621,    0,
      491,  461,  482,  473,  387,  423,  465,  471,  469,  479,
      492,  458,  456,  447,  314,  455,  501,  504,  453,  445,
      637,  490,  519,  438,  443,  481,  538,  516,  541,  434,
      551,  544,  434,  581,  553,  555,  421,  432,  408,  563,
      410,  408,  398,  591,  599, 1148,  570,  391,  397,  383,

      607,  616,  377,  364,  639,  650,  358,  344,  652,  654,
      618,  333,  336,  623,  663,  631,  325,  665,  634,  296,
      642,  276,  667,  674,  211,   52,  677,  679,  683,  691,
      693,  681,  695,  702,  704, 1148,  739,  743,  755,  766,
      777,  786,  795,  801,  814,  827,  839,  850,  860,  872,
      884,  895,  906,  917,  920,  930,  941,  953,  963,  974,
      984,  990, 1001, 1012, 1022, 1032, 1044, 1056, 1059, 1071,
     1074, 1086, 1089, 1101, 1104, 1116, 1119, 1131, 1134
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      236,    1,  236,  236,  237,  237,  238,  239,  236,  239,
       10,   10,  237,  240,  238,  238,  241,  242,  243,   10,
      244,  236,  245,  246,  242,   25,   25,   25,  241,  247,
      240,  248,  241,   25,  236,   25,  249,  250,  244,  236,
      241,  245,  236,  245,  246,   25,   25,   25,   25,   25,
       33,  247,   52,  236,  248,  251,  249,  236,  236,  250,
      236,   40,  241,  236,  236,  245,   25,   25,   25,   25,
       25,  252,  236,  236,  244,   64,  244,  236,   25,   25,
       25,   25,   25,  236,  253,  254,  252,  236,  236,  251,
      255,   25,   25,   25,   25,  236,  251,  253,   98,  236,

      254,  256,  243,  257,   25,  258,   33,  243,  236,  243,
      259,  256,  236,  243,  236,  257,  236,   25,  260,  260,
      120,   55,  243,  261,  262,  236,  236,  236,  236,  236,
      120,  120,  120,   55,   98,  236,  263,  262,  236,  236,
      259,  236,  236,  120,  120,   55,  236,  251,  263,  149,
      236,  243,  236,  236,  120,  120,   55,  243,  236,  243,
      243,  236,  236,  120,  120,   55,  243,  261,  236,  236,
      264,  120,  265,  236,  236,  266,  130,  267,  236,  236,
      236,  266,  236,  236,  267,  268,  236,  236,  236,  269,
      236,  236,  236,  236,  269,  236,  236,  236,  236,  236,

      270,  236,  236,  236,  271,  265,  236,  236,  236,  271,
      272,  236,  236,  272,  273,  236,  236,  273,  274,  236,
      275,  236,  236,  275,  236,  236,  236,  276,  277,  236,
      277,  278,  278,  279,  279,    0,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236
    } ;

static const flex_int16_t yy_nxt[1185] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    4,    4,    9,
        4,    4,    4,    4,    4,    8,    4,    4,    8,    8,
       10,    8,    8,    8,    8,    8,    8,    8,   11,    8,
       12,    8,    8,    8,    8,    4,   13,   13,   13,   13,
       17,   17,   18,   23,   19,   24,   18,   26,   34,   20,
       27,   21,   81,   28,   34,   22,   17,   17,   13,   13,
       19,   29,   29,   43,   43,   20,   67,   21,   44,   44,
       31,   22,   21,   17,   17,   34,   22,   19,   34,   25,
       34,   49,  227,   47,   21,   33,   33,   48,   69,   19,
       60,   60,   35,   61,   36,   35,   21,   35,   90,   90,

       22,   33,   33,   29,   29,   19,   34,  236,   35,   34,
       36,   35,   21,   35,   21,   70,   22,   43,   46,   51,
       51,   68,   65,   34,   29,   29,   35,   94,   53,   35,
       21,   35,   34,   31,   22,   21,   54,   54,   34,   22,
       56,   56,   34,   35,   93,   71,   35,   43,   35,   33,
       33,   92,   44,   19,   66,   58,   35,  101,  101,   35,
       21,   35,   39,   62,   63,   39,   64,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   40,   64,   39,   39,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   39,   29,   29,

       51,   51,  236,   34,  236,   60,   60,   43,   61,   21,
       54,   54,   44,   22,   51,   51,  105,   35,   56,   56,
       35,   35,   35,   53,   35,   21,   35,   54,   54,   22,
       56,   56,   34,   73,   35,   34,  118,   35,   34,   35,
       63,   63,  226,   82,  236,   58,   34,   79,   94,   90,
       90,  236,   39,   75,   54,   39,   76,   39,   39,   39,
       77,   39,   76,   77,   39,   77,   40,   76,   39,   39,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   39,   34,   91,
       91,  106,  106,   83,   84,   84,   34,   34,   95,   38,

       94,   86,  225,   87,  107,  107,   34,  131,   34,   88,
       75,   54,   84,   84,  133,   90,   90,   77,  222,   86,
       77,   34,   77,   40,   97,   97,  144,   96,   97,   97,
      236,   86,  131,   38,  172,   86,  145,   99,  131,  109,
      101,  101,  131,  100,   84,   84,  131,  111,  111,   38,
      220,   86,  155,   87,  111,  111,  107,  107,  217,   88,
       91,   91,  113,  216,   19,  141,  141,   35,  213,  126,
       35,   21,   35,   97,   97,  122,  114,  114,   38,  212,
       86,   38,   99,   86,  141,  141,  114,  114,  100,  115,
      115,   38,  208,   86,  111,  111,   35,  124,  124,   35,

      131,   35,   38,  207,   86,  114,  114,  156,  204,  113,
       38,  131,   86,  124,  124,  136,  136,  164,   38,  203,
       86,  202,   86,  117,  106,  106,  141,  141,   19,  199,
      147,   35,  124,  124,   35,   21,   35,   38,  198,   86,
      197,  236,  193,  120,  148,  148,  165,  131,  171,  171,
      192,   86,  191,  121,  115,  115,  173,  173,  188,  159,
      187,   35,  161,  161,   35,  180,   35,   38,  179,   86,
      175,  131,  161,  161,  174,  128,  129,   38,  170,   86,
      168,  168,  181,  181,  169,   38,  167,   86,  117,  115,
      115,  177,  177,  161,  161,  166,   35,  163,   38,   35,

       86,   35,  168,  168,  162,  168,  168,   38,  160,   86,
       38,  158,   86,  157,  131,  154,  117,  184,  184,  153,
      173,  173,  152,  117,  130,  130,  146,   35,   19,  131,
       35,   35,   35,  143,   35,  142,   35,  130,  130,  177,
      177,   19,  186,  186,   35,  181,  181,   35,  140,   35,
      134,  117,  181,  181,  184,  184,  186,  186,  183,  127,
      132,  136,  136,  123,  194,  194,   38,  110,   86,  108,
      138,  201,  201,  128,  129,  103,  139,  130,  130,  117,
       40,   19,  184,  184,   35,   89,  117,   35,  117,   35,
      148,  148,  194,  194,   80,   38,   78,   86,  196,  150,

      194,  194,   74,  189,  129,  151,  136,  136,  201,  201,
       40,   38,   34,   86,  200,  138,  117,  206,  206,  214,
      214,  139,  148,  148,  214,  214,  196,   38,   34,   86,
       50,  150,  219,  219,  196,  219,  219,  151,  171,  171,
      209,  209,   19,  223,  223,   35,   41,  211,   35,   40,
       35,  206,  206,  209,  209,  209,  209,   18,  236,   38,
      211,  236,  211,  236,  209,  209,  209,  209,  223,  223,
       16,  211,   16,  211,  117,  223,  223,  117,  228,  228,
      228,  228,  233,  233,  230,  230,   16,  117,  236,  117,
      129,  232,  230,  230,  230,  230,  233,  233,  117,  232,

      117,  232,  117,  230,  230,  230,  230,  236,  236,  117,
      232,  236,  232,  236,  236,  236,  236,  236,  196,  236,
      236,  236,  236,  236,  236,  236,  196,  236,  196,  236,
      236,  236,  236,  236,  236,  236,  236,  196,  236,  196,
       14,   14,   14,   15,   15,  236,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   18,   18,   18,   18,
      236,  236,   18,  236,   18,  236,   18,   30,   30,   30,
      236,  236,  236,   30,  236,   30,  236,   30,   32,   32,
       32,   32,  236,  236,  236,  236,   32,   34,   34,   34,
       34,  236,   34,   34,   34,   34,   34,   34,   37,  236,

       37,   39,   39,  236,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   45,   45,  236,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       52,   52,   52,  236,  236,   52,   52,   52,   52,   52,
       52,   55,   55,   55,  236,  236,   55,   55,   55,  236,
       55,   57,   57,   57,  236,  236,  236,   57,  236,  236,
      236,   57,   59,   59,   59,   59,   59,   59,   59,   59,
      236,   59,   59,   59,   59,   72,   72,   72,  236,  236,
      236,  236,  236,  236,  236,   72,   85,   85,   85,  236,

       85,   85,   85,  236,  236,  236,   85,   98,   98,   98,
      236,   98,   98,   98,  236,  236,  236,   98,  102,  102,
      102,  104,  104,  104,  104,  236,  104,  236,  104,  104,
      104,  112,  112,  112,  236,  236,  236,  112,  236,  236,
      236,  112,  116,  116,  116,  236,  236,  116,  116,  116,
      236,  116,  236,  116,  119,  119,  119,  119,  236,  119,
      236,  119,  119,  119,  125,  125,  125,  236,  236,  236,
      236,  236,  236,  236,  125,  131,  131,  131,  131,  236,
      131,  131,  131,  236,  131,  135,  135,  135,  236,  135,
      135,  137,  137,  137,  236,  137,  137,  137,  236,  236,

      236,  137,  149,  149,  149,  236,  149,  149,  149,  236,
      236,  236,  149,  176,  176,  176,  176,  236,  176,  236,
      176,  236,  176,  178,  178,  178,  236,  236,  178,  236,
      178,  236,  178,  182,  182,  182,  236,  236,  236,  182,
      236,  236,  236,  236,  182,  185,  185,  185,  236,  236,
      236,  185,  236,  236,  236,  236,  185,  190,  190,  190,
      195,  195,  195,  236,  236,  236,  195,  236,  236,  236,
      236,  195,  205,  205,  205,  210,  210,  210,  236,  236,
      210,  210,  236,  236,  236,  236,  210,  215,  215,  215,
      218,  218,  218,  236,  236,  218,  218,  236,  236,  236,

      236,  218,  221,  221,  221,  224,  224,  224,  236,  236,
      236,  224,  236,  236,  236,  236,  224,  229,  229,  229,
      231,  231,  231,  236,  236,  231,  231,  236,  236,  236,
      236,  231,  234,  234,  234,  235,  235,  235,  236,  236,
      235,  235,  236,  236,  236,  236,  235,    3,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236
    } ;

static const flex_int16_t yy_chk[1185] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        8,    8,   11,    9,    8,    9,   12,   11,   69,    8,
       11,    8,   69,   12,   46,    8,   10,   10,   13,   13,
       10,   14,   14,   23,   42,   10,   46,   10,   23,   42,
       14,   10,   14,   17,   17,   48,   14,   17,   26,   10,
       27,   27,  226,   26,   17,   18,   18,   26,   48,   18,
       38,   38,   18,   38,   18,   18,   18,   18,   74,   74,

       18,   25,   25,   29,   29,   25,   47,   29,   25,   49,
       25,   25,   25,   25,   29,   49,   25,   43,   25,   30,
       30,   47,   43,   92,   31,   31,   30,   92,   30,   30,
       30,   30,   50,   31,   30,   31,   32,   32,   80,   31,
       37,   37,   81,   32,   81,   50,   32,   44,   32,   33,
       33,   80,   44,   33,   44,   37,   33,   86,   86,   33,
       33,   33,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   41,   41,

       51,   51,   41,   93,   51,   60,   60,   66,   60,   41,
       54,   54,   66,   41,   52,   52,   93,   54,   56,   56,
       54,   52,   54,   52,   52,   52,   52,   55,   55,   52,
       57,   57,  105,   56,   55,   67,  105,   55,   70,   55,
       63,   63,  225,   70,   63,   57,   82,   67,   82,   89,
       89,   63,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   71,   79,
       79,   94,   94,   71,   72,   72,   83,  118,   83,   72,

      118,   72,  222,   72,   95,   95,   79,  121,   94,   72,
       75,   75,   84,   84,  121,   90,   90,   75,  220,   84,
       75,   95,   75,   75,   97,   97,  132,   84,   85,   85,
       90,   97,  132,   85,  165,   85,  133,   85,  165,   97,
      101,  101,  133,   85,   87,   87,  144,  102,  102,   87,
      217,   87,  144,   87,  111,  111,  107,  107,  213,   87,
       91,   91,  102,  212,   91,  127,  127,   91,  208,  111,
       91,   91,   91,   98,   98,  107,  103,  103,   98,  207,
       98,  103,   98,  103,  140,  140,  108,  108,   98,  104,
      104,  108,  204,  108,  112,  112,  104,  110,  110,  104,

      145,  104,  110,  203,  110,  114,  114,  145,  200,  112,
      114,  155,  114,  123,  123,  136,  136,  155,  123,  199,
      123,  198,  136,  104,  106,  106,  141,  141,  106,  193,
      136,  106,  124,  124,  106,  106,  106,  124,  192,  124,
      191,  141,  189,  106,  148,  148,  156,  156,  164,  164,
      188,  148,  187,  106,  115,  115,  166,  166,  183,  148,
      180,  115,  152,  152,  115,  175,  115,  152,  174,  152,
      170,  164,  158,  158,  169,  115,  115,  158,  163,  158,
      160,  160,  176,  176,  162,  160,  159,  160,  115,  116,
      116,  172,  172,  161,  161,  157,  116,  154,  161,  116,

      161,  116,  167,  167,  153,  168,  168,  167,  151,  167,
      168,  147,  168,  146,  172,  143,  176,  178,  178,  142,
      173,  173,  139,  116,  119,  119,  134,  173,  119,  131,
      173,  119,  173,  129,  119,  128,  119,  120,  120,  177,
      177,  120,  179,  179,  120,  182,  182,  120,  126,  120,
      122,  178,  181,  181,  185,  185,  186,  186,  177,  113,
      120,  125,  125,  109,  190,  190,  125,  100,  125,   96,
      125,  197,  197,  181,  181,   88,  125,  130,  130,  182,
       77,  130,  184,  184,  130,   73,  181,  130,  185,  130,
      137,  137,  194,  194,   68,  137,   65,  137,  190,  137,

      195,  195,   58,  184,  184,  137,  138,  138,  201,  201,
       39,  138,   36,  138,  194,  138,  184,  202,  202,  211,
      211,  138,  149,  149,  214,  214,  194,  149,   34,  149,
       28,  149,  216,  216,  195,  219,  219,  149,  171,  171,
      205,  205,  171,  221,  221,  171,   22,  205,  171,   21,
      171,  206,  206,  209,  209,  210,  210,   20,  206,   19,
      209,  206,  210,  206,  215,  215,  218,  218,  223,  223,
       16,  215,   15,  218,  205,  224,  224,  221,  227,  227,
      228,  228,  232,  232,  229,  229,    7,  209,    3,  210,
      223,  229,  230,  230,  231,  231,  233,  233,  215,  230,

      218,  231,  223,  234,  234,  235,  235,    0,    0,  224,
      234,    0,  235,    0,    0,    0,    0,    0,  229,    0,
        0,    0,    0,    0,    0,    0,  230,    0,  231,    0,
        0,    0,    0,    0,    0,    0,    0,  234,    0,  235,
      237,  237,  237,  238,  238,    0,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  239,  239,  239,  239,
        0,    0,  239,    0,  239,    0,  239,  240,  240,  240,
        0,    0,    0,  240,    0,  240,    0,  240,  241,  241,
      241,  241,    0,    0,    0,    0,  241,  242,  242,  242,
      242,    0,  242,  242,  242,  242,  242,  242,  243,    0,

      243,  244,  244,    0,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  246,  246,    0,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      247,  247,  247,    0,    0,  247,  247,  247,  247,  247,
      247,  248,  248,  248,    0,    0,  248,  248,  248,    0,
      248,  249,  249,  249,    0,    0,    0,  249,    0,    0,
        0,  249,  250,  250,  250,  250,  250,  250,  250,  250,
        0,  250,  250,  250,  250,  251,  251,  251,    0,    0,
        0,    0,    0,    0,    0,  251,  252,  252,  252,    0,

      252,  252,  252,    0,    0,    0,  252,  253,  253,  253,
        0,  253,  253,  253,    0,    0,    0,  253,  254,  254,
      254,  255,  255,  255,  255,    0,  255,    0,  255,  255,
      255,  256,  256,  256,    0,    0,    0,  256,    0,    0,
        0,  256,  257,  257,  257,    0,    0,  257,  257,  257,
        0,  257,    0,  257,  258,  258,  258,  258,    0,  258,
        0,  258,  258,  258,  259,  259,  259,    0,    0,    0,
        0,    0,    0,    0,  259,  260,  260,  260,  260,    0,
      260,  260,  260,    0,  260,  261,  261,  261,    0,  261,
      261,  262,  262,  262,    0,  262,  262,  262,    0,    0,

        0,  262,  263,  263,  263,    0,  263,  263,  263,    0,
        0,    0,  263,  264,  264,  264,  264,    0,  264,    0,
      264,    0,  264,  265,  265,  265,    0,    0,  265,    0,
      265,    0,  265,  266,  266,  266,    0,    0,    0,  266,
        0,    0,    0,    0,  266,  267,  267,  267,    0,    0,
        0,  267,    0,    0,    0,    0,  267,  268,  268,  268,
      269,  269,  269,    0,    0,    0,  269,    0,    0,    0,
        0,  269,  270,  270,  270,  271,  271,  271,    0,    0,
      271,  271,    0,    0,    0,    0,  271,  272,  272,  272,
      273,  273,  273,    0,    0,  273,  273,    0,    0,    0,

        0,  273,  274,  274,  274,  275,  275,  275,    0,    0,
        0,  275,    0,    0,    0,    0,  275,  276,  276,  276,
      277,  277,  277,    0,    0,  277,  277,    0,    0,    0,
        0,  277,  278,  278,  278,  279,  279,  279,    0,    0,
      279,  279,    0,    0,    0,    0,  279,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "part1.l"
#line 2 "part1.l"
    int count = 0; 
    int classCount = 0;
    int inhCount = 0;
    char *className[100];
    char *array[100];
    int classIndex = 0;
    int objCount = 0;
    char *objName;
    int objIndex=0;
    int constCount=0;
    char *constructorName;
    int constIndex=0;
    int prevClassLineNo = -1;
    int prevInhLineNo = -1;
    int prevConstLineNo = -1;
    int prevObjLineNo = -1;
#line 802 "lex.yy.c"
#line 803 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "part1.l"

#line 1022 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 237 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1148 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 20 "part1.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 21 "part1.l"
{
    if (yylineno != prevInhLineNo) {
        inhCount++;
        classCount++;
        prevInhLineNo = yylineno;
    }    

    int i=0;
    array[i] = strtok(yytext," \n\t\r{");

    while(array[i]!=NULL)
    {
    array[++i] = strtok(NULL," \n\t\r{");
    }
    i=0;
    while(strcmp(array[i],"class")!=0){
        i++;
    }
    i++;
    // strcpy(className[classIndex],array[i]);
     className[classIndex]= array[i];
        printf("clasname - %s\n",className[classIndex]);
        for(int j=0;j<strlen(className[classIndex]);j++){
            if(className[classIndex][j]=='{'){
                className[classIndex][j] = '\0';
                // printf("after- %s\n",className[classIndex]);
            }    
        }
    classIndex++;
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "part1.l"
{
        if (yylineno != prevClassLineNo) {
            classCount++;
            prevClassLineNo = yylineno;
        }    

        int i=0;
        array[i] = strtok(yytext," \n\t\r{");

        while(array[i]!=NULL)
        {
        array[++i] = strtok(NULL," \n\t\r{");
        }
        i=0;
        while(strcmp(array[i],"class")!=0){
            i++;
        }
        i++;
        // strcpy(className[classIndex],array[i]);
        className[classIndex]= array[i];
        // printf("classname - %s\n",className[classIndex]);
        for(int j=0;j<strlen(className[classIndex]);j++){
            if(className[classIndex][j]=='{'){
                className[classIndex][j] = '\0';
                // printf("after- %s\n",className[classIndex]);
            }    
        }
        classIndex++;
    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 80 "part1.l"
{
        int i=0;
        array[i] = strtok(yytext," \n\t\r{[<");
        while(array[i]!=NULL)
        {
        array[++i] = strtok(NULL," \n\t\r{[<");
        }
        objName = array[0];
        int j = 0;
        while(className[j]!=NULL){
            if(strcmp(className[j],objName)==0){
                objCount++;
                break;
            }    
            j++;
        }
 }   
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 98 "part1.l"
{
    // printf("---%s---\n",yytext);
    int i=0;
    array[i] = strtok(yytext," \n\t\r(");
    while(array[i]!=NULL) {
    array[++i] = strtok(NULL," \n\t\r(");
    }
    constructorName=array[0];
    if (strcmp(array[0],"public")==0 || strcmp(array[0],"private")==0 || strcmp(array[0],"protected")==0){
        constructorName=array[1];
    }
    constIndex++;
    int k=0;
    // printf("//%s\n", constructorName);
    while(className[k]!=NULL){
        // printf("names-%s\n",className[k]);
        if(strcmp(className[k], constructorName)==0){
            constCount++;
            break;
        }
        k++;
    }

}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 "part1.l"
;
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 123 "part1.l"
{yylineno++;} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 124 "part1.l"
ECHO;
	YY_BREAK
#line 1221 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 237 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 237 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 236);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 124 "part1.l"


int yywrap(){} 

int main(){ 
  
    FILE *fp; 
    char filename[50]; 
    printf("Enter the filename: \n"); 
    scanf("%s",filename); 
    fp = fopen(filename,"r"); 
    yyin = fp; 
    
    yylex(); 
    int i = 0;
    while(className[i]!=NULL){
        // printf("stored classname - %s//\n",className[i]);
        for(int j=0;j<strlen(className[i]);j++){
            if(className[i][j]=='{'){
                className[i][j] = '\0';
                // printf("after- %s\n",className[i]);
            }    
        }
        i++;
    }  
    
    // i=0;
    // j = 0;
    // while(constName[i]!=NULL){
    //     j=0;
    //     while(className[j]!=NULL){
    //         if(strcmp(className[j],constName[i])==0){
    //             constCount++;
    //             break;
    //         }    
    //         j++;
    //     }
    //     i++;
    // }
    printf("Object Declarations - %d\n",objCount);
    printf("Class Definitions - %d\nConstructor Definitions - %d\nInherited Class Definitions - %d\n", classCount, constCount, inhCount); 
    return 0; 
} 
